
platform :ios, '9.0'

target 'HYYSDKGroup' do

  # use_frameworks!
pod 'Masonry'
pod 'SVProgressHUD'
# 短信验证
pod 'MOBFoundation_IDFA'

pod 'SMSSDK'

# 友盟分享
pod 'UMengUShare/Social/Sina'
# 地图
pod 'AMap3DMap', '~> 4.1.0'  #3D地图SDK
#pod 'AMap2DMap' #2D地图SDK (2D和3D不能同时使⽤)
pod 'AMapSearch' #搜索服务SDK
pod 'HMNumberStringConvert'


end
